modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/svennieke/StatuesMod/issues"

[[mods]]
modId="structurecompass"
version="${file.jarVersion}"
displayName="Structure Compass Mod"
displayURL="https://minecraft.curseforge.com/projects/statues"
authors="Mrbysco"
description='''
Adds compasses that point to their individual structures.
'''

[[dependencies.structurecompass]]
modId="forge"
mandatory=true
versionRange="[28,)"
ordering="NONE"
side="BOTH"

[[dependencies.structurecompass]]
modId="minecraft"
mandatory=true
versionRange="[1.14.4]"
ordering="NONE"
side="BOTH"