modLoader="javafml"
loaderVersion="[38,)"
issueTrackerURL="https://github.com/Mrbysco/StructureCompass/issues"
license="MIT"

[[mods]]
modId="structurecompass"
version="${file.jarVersion}"
displayName="Structure Compass Mod"
displayURL="https://www.curseforge.com/minecraft/mc-mods/structure-compass"
authors="Mrbysco"
description='''
Adds a compass that can locate structures
'''
[[dependencies.structurecompass]]
modId="minecraft"
mandatory=true
versionRange="[1.18,1.19)"
ordering="NONE"
side="BOTH"