modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/Mrbysco/StructureCompass/issues"

[[mods]]
modId="structurecompass"
version="${file.jarVersion}"
displayName="Structure Compass Mod"
displayURL="https://www.curseforge.com/minecraft/mc-mods/structure-compass"
authors="Mrbysco"
description='''
Adds compasses that point to their individual structures.
'''